name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Run tests
        run: go test -v ./...

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/tracknme:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/tracknme:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tracknme \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tracknme:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=winter-return-459915-s4:us-central1:tracknme-db \
            --set-env-vars="ENVIRONMENT=${{ secrets.ENVIRONMENT }},DATABASE_POSTGRES=${{ secrets.DATABASE_POSTGRES }},ZIP_CODE_API=${{ secrets.ZIP_CODE_API }},REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PORT=${{ secrets.REDIS_PORT }},REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" 
